name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        TAG=$(date +%s)
        echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
        docker build . --tag ghcr.io/$GITHUB_USERNAME/workshop-action:$TAG
        docker push ghcr.io/$GITHUB_USERNAME/workshop-action:$TAG
